FROM node:16-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install

# Bundle app source. Not strictly necessary since we are using volumes but leave it in as a reminder.
COPY . .

EXPOSE 3000

CMD [ "npm", "run", "start" ]